version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: upokari/Dockerfile
    container_name: upokari_web
    command: python manage.py runserver 0.0.0.0:6000
    volumes:
      - ./upokari:/app  # Mount the Django project directory
      - ./upokari/db.sqlite3:/app/db.sqlite3  # SQLite database (proxy)
    ports:
      - "6000:6000"
    environment:
      SECRET_KEY: "${SECRET_KEY}"  # From the .env file
      DEBUG: "False"
      ROOT_URLCONF: "upokari.urls"
      WSGI_APPLICATION: "upokari.wsgi.application"
      LANGUAGE_CODE: "en-us"
      TIME_ZONE: "UTC"
      USE_I18N: "True"
      USE_TZ: "True"
      ENGINE: "$ENGINE"
      NAME: "NAME"
      USER: ""
      PASSWORD: ""
      HOST: ""
      PORT: ""
      SDK_URL: "${SDK_URL}"
      MONGO_URI: "mongodb://$MONGO_USER:$MONGO_PASSWORD@mongo:27017/$MONGO_DB?authSource=admin"  # MongoDB connection string

  mongo:
    image: mongo:latest
    container_name: upokari_mongo
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: "$MONGO_DB"
      MONGO_INITDB_ROOT_USERNAME: "$MONGO_USER"
      MONGO_INITDB_ROOT_PASSWORD: "$MONGO_PASSWORD"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
