# Generated by Django 5.1.4 on 2025-02-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpoofAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='spoof_attempts/')),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(default='Unknown', max_length=255)),
            ],
        ),
    ]
